### PR TITLE
Add `on-call:list` command to list members within on-call teams

### PR DESCRIPTION
**Pull request by dblandin**
Requires a valid `OPSGENIE_API_KEY` to be present within the environment (https://artsy.app.opsgenie.com/settings/api-key-management).

```
$ artsy on-call:list --teamName Engineering
Devon Blandin
Jon Allured
...

$ artsy on-call:list --teamName Engineering --randomize
Jon Allured
Devon Blandin
...

$ artsy on-call:list --team-name Engineering --randomize --split 2
Jon Allured
...

Devon Blandin
...
```

cc/ @zephraph @pepopowitz

### CODE REVIEW

**Comment by zephraph** [comment]
Oh, this is cool! Is it to help with on-call scheduling?

**Comment by dblandin** [comment]
> Oh, this is cool! Is it to help with on-call scheduling?

@zephraph Yep! That's what I'm using it for now.

I wonder if I should move this under a namespace. Maybe something like: `opsgenie:users:list --team-name Engineering`? What do you think?

**Comment by zephraph** [comment]
I don't think having a namespace would but that's a bit of a long namespace. It might be best to not have a command mentioning a specific service. 

So maybe like...  `artsy onCall --listAll`

**Comment by dblandin** [comment]
> It might be best to not have a command mentioning a specific service.

@zephraph For sure! Great idea for the more general `onCall` namespace :+1:. I think `list` should be its own command vs a flag on an `onCall` command so I've left that in.

I've also gone ahead and updated the usage examples in the PR description.

**Comment by jonallured** [comment]
Wooo, this is great!! Can you help me understand the team name stuff? It looks like one can either pass the name or get all users that they have access to, is that right? I guess I'm wondering when we would ever pass anything other than "Engineering" for this flag and if that would ever produce different results than passing no team name at all. Like, do we actually need this feature? Maybe I don't get it.

I think it would be good to have a few tests around this if for no other reason than to support future work. We do have the ability to mock network requests as seen here:

https://github.com/artsy/artsy-cli/blob/d8896908517037c113a39b99a91b189a5e5c5181/test/commands/identify.test.ts

What do you think?

**Comment by dblandin** [comment]
Hey @jonallured! Sorry for the delayed response here! Was out on vacation for a bit.

> Wooo, this is great!! Can you help me understand the team name stuff? It looks like one can either pass the name or get all users that they have access to, is that right? I guess I'm wondering when we would ever pass anything other than "Engineering" for this flag and if that would ever produce different results than passing no team name at all. Like, do we actually need this feature? Maybe I don't get it.

There is a slight difference in results as we have one user configured in OpsGenie who is not also part of the Engineering on-call rotation, so he shows up when you don't scope to the Engineering Team. I've also had some discussions recently regarding additional teams so having the --team flag allows you to specify which to scope to.

> I think it would be good to have a few tests around this if for no other reason than to support future work. We do have the ability to mock network requests as seen here:

Definitely agree about the tests! I'll work on that.

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.3.0`](https://github.com/artsy/artsy-cli/releases/tag/v0.3.0) :rocket:

**Pull request merged**
