### PR TITLE
feat: add scheduled:standup-reminder task

### PR DESCRIPTION
**Pull request by dblandin**
This is the first of a few tasks that I plan to migrate over to the CLI to simplify some of our culture ops automation.

The idea is to invoke this task on a similar schedule (every Monday morning at 9am ET) via GitHub Actions (probably in the artsy/README repo).

https://github.com/artsy/peril-settings/blob/master/tasks/standupReminder.ts

#FF #FutureFriday

**Example**

The output here is intended for a Slack destination. The output includes formatted Slack @-mentions and links.

```
$ artsy scheduled:standup-reminder
<@U2JA8FG15>, <@U0QRCNUAV> based on our on-call schedule, you’ll be running the Monday standup at 12:00 noon NYC time. Here are the docs <https://github.com/artsy/README/blob/master/events/open-standup.md|on GitHub>. Add new standup notes <https://www.notion.so/artsy/Standup-Notes-28a5dfe4864645788de1ef936f39687c|in Notion>.
```

Screen Shot 2021-02-06 at 1 35 51 AM

### CODE REVIEW

**Comment by dblandin** [comment]
I'm thinking about reorganizing this and the corresponding artsy/README PR: https://github.com/artsy/README/pull/367

- For any command that is expected to format output for Slack, support a `--format` string argument, defaulting to `plain`.
- If `--format=plain`, output a plain text representation of the output
- If `--format=slack`, output a JSON object adhering to the [Slack message payload spec](https://api.slack.com/reference/messaging/payload)

That should give us the ability to format richer input here and rely less on downstream clients to reformat output for Slack. Thoughts?

**Review by jonallured — APPROVED** [review]
I love this direction and thinking, very cool stuff @dblandin!! 🙌 ❤️ 🏆

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.4.0`](https://github.com/artsy/artsy-cli/releases/tag/v0.4.0) :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.4.0`](https://github.com/artsy/artsy-cli/releases/tag/v0.4.0) :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.4.0`](https://github.com/artsy/artsy-cli/releases/tag/v0.4.0) :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.4.0`](https://github.com/artsy/artsy-cli/releases/tag/v0.4.0) :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.4.0`](https://github.com/artsy/artsy-cli/releases/tag/v0.4.0) :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.4.0`](https://github.com/artsy/artsy-cli/releases/tag/v0.4.0) :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.4.0`](https://github.com/artsy/artsy-cli/releases/tag/v0.4.0) :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in [`v0.4.0`](https://github.com/artsy/artsy-cli/releases/tag/v0.4.0) :rocket:

**Pull request merged**
