### PR TITLE
Add dry run of deploy step

### PR DESCRIPTION
**Pull request by jonallured**
Let's see what CircleCI thinks of it.

### CODE REVIEW

**Comment by jonallured** [comment]
Going to merge this and then create a release branch and push it, hoping that when that happens I see the dry run output.

**Comment by jonallured** [comment]
Ok, this worked, here's the workflow that shows both test and publish jobs were triggered:

https://circleci.com/workflow-run/4b646d3a-768a-4f54-bbc3-0b865b7e8a91

And then here we can see the job for publishing:

https://circleci.com/gh/artsy/artsy-cli/25

And if you open the "Publish package" step, you'll see the `npm publish` output.

**Comment by artsyit** [comment]
:rocket: PR was released in v0.0.2 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v0.0.2 :rocket:

**Pull request merged**
